### ISSUE TITLE
Simultaneous switching text style and non-text style (graphics)

### ISSUE THREAD

**Issue by Linci** [ozzik/swap-styles#1]

**Comment by ozzik** [comment]
Hey there, can you please elaborate on this? Kinda hard to understand the exact problem :) Thanks!

**Comment by Linci** [comment]
![2015-11-30 11 05 28](https://cloud.githubusercontent.com/assets/3479164/11462665/49d0ec6e-9752-11e5-81d4-d8bd6ee966fc.png)

**Comment by ozzik** [comment]
Thanks for the visual explanation, so if I got this right: you wish to be able to swap styles of more than 2 selected layers, by matching their types? (in your demo, selecting all 4 layers having the plugin swap the two different styles [gray and blue] across all 4 layers)
