### ISSUE TITLE
Stop working in Sketch 3.8.2

### ISSUE THREAD

**Issue by asyla** [ozzik/swap-styles#2]
Hi there Oz,

Love your plugin so much! But it has unexpectedly stopped working in Sketch Version 3.8.2 (29753). Need your help, please)

Mac OS X El Capitan 10.11.4 (15E65)

![screen shot 2016-05-25 at 1 01 08 pm](https://cloud.githubusercontent.com/assets/14801014/15536223/15a01674-2279-11e6-9d5c-3584c00e66cd.png)

**Comment by jberk-godaddy** [comment]
Same here!  Broken with sketch update.

**Comment by ozzik** [comment]
Thanks for spotting this!
Fixed! Please update your plugin and lmk if there's any problem :)

**Comment by jberk-godaddy** [comment]
Oh sweet thanks!

_Joshua Berk_
480.232.7074

**Comment by asyla** [comment]
Oz, thank you so much!

**Comment by ozzik** [comment]
![Party](https://media.giphy.com/media/NHFiGCmtY9lT2/giphy.gif)
