### ISSUE TITLE
Text style swapping issue in Sketch 40.2 

### ISSUE THREAD

**Issue by jydesign** [ozzik/swap-styles#5]
Hi, with Sketch 40.2, I'm unable to swap text styles, but object style swapping works. Is this a known issue? thanks

**Comment by ozzik** [comment]
Hey and thanks for reporting this!

You're right, it's actually a deprecation bug Bohemian have warned me about but I was too lazy to fix in time :) Anyway, it's fixed now. Please try it and lmk how it goes :)
